version: "3.8"
services:
    app:
      build: ./scaffoldthis/
      container_name: scaffoldthis-other
    postgres:
      image: postgres
      container_name: scaffoldthis-postgres
      restart: unless-stopped
      working_dir: /application
      volumes:
        - postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=samiam
        - POSTGRES_DB=scaff
        - POSTGRES_USER=sam
      ports:
        - "5432:5432"
    rabbitmq:
      image: rabbitmq:3.8.9-alpine
      container_name: scaffoldthis-rabbitmq
      hostname: rabbitmq
      restart: unless-stopped
      ports:
        - 5672:5672
      volumes:
        - rabbitmq:/var/lib/rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=sam
        - RABBITMQ_DEFAULT_PASS=samiam
    redis:
      image: redis
      container_name: scaffoldthis-redis
      restart: unless-stopped
      ports:
        - "6379:6379"
      volumes:
        - redis:/data
    grafana:
      container_name: scaffoldthis-grafana
      image: grafana/grafana:6.2.1
      ports:
        - "3000:3000"
      volumes:
        - grafana:/var/lib/grafana
      restart: always
      environment:
        - GF_SECURITY_ADMIN_USER=sam
        - GF_SECURITY_ADMIN_PASSWORD=samiam
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
      container_name: scaffoldthis-elasticsearch
volumes:
  postgres:
  redis:
  rabbitmq:
  grafana:
